# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Deployment

on: [push]


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Copy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'ubuntu'
        server: '${{ secrets.SERVER_IP }}'
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        local_path: './*'
        remote_path: '/home/ubuntu/mobile'
        args: '-o ConnectTimeout=5'